---
env:
  browser: true
  es2020: true
  jest: true
  node: true
  # extends: 
  #- airbnb-base
parserOptions:
  ecmaVersion: 11
  sourceType: module
settings: 
  import/resolver:
    node:
      extensions:
      - ".js"
      - ".jsx"
      - ".ts"
      - ".tsx"
      moduleDirectory:
      - node_modules
      - src/
      paths:
      - src
rules: 
  indent:
  - error
  - 4
  import/extensions:
  - error
  - ignorePackages
  - js: never
    jsx: never
    tsx: never
    ts: never
